## Python Challenge 6- NumPy

In [ ]:
# Create a numpy array called ‘height in inches’ from a list 10 of numbers: [66, 68, 71, 64, 61, 74, 64, 65, 70, 71].

# Create a new array called ‘height_in_feet’ and make its values equal to the values in the first array divided by 12.
# Create a 5x5 array of zeros. 
# Create an array of random floating point numbers between 0 and 100. 
# Create an array of numbers from 0 to 75 in increments of 5.


In [1]:
import numpy as np

In [2]:
# Create a numpy array called ‘height in inches’ from a list 10 of numbers: [66, 68, 71, 64, 61, 74, 64, 65, 70, 71].

height_in_inches = np.array([66, 68, 71, 64, 61, 74, 64, 65, 70, 71])
print(height_in_inches )
type(height_in_inches )
height_in_inches.dtype

[66 68 71 64 61 74 64 65 70 71]


dtype('int32')

In [3]:
# Create a new array called ‘height_in_feet’ and make its values equal to the values in the first array divided by 12.

height_in_feet = (height_in_inches/12)
print(height_in_feet)

[5.5        5.66666667 5.91666667 5.33333333 5.08333333 6.16666667
 5.33333333 5.41666667 5.83333333 5.91666667]


In [5]:
# Create a 5x5 array of zeros. 
a = np.zeros((5,5))
print(a.dtype)
print(a)

float64
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
# Create an array of random floating point numbers between 0 and 100.
a = (np.random.random(22)) * 100
print(a)
a.dtype

[36.94829322 40.61232351 54.68778072 72.95558762 72.33722058 57.05517884
 27.56454615  0.95748724 59.81002322 77.13240241  4.74155595 84.55234234
 86.43629924  1.2709544  76.22330659 88.97305218 84.74200968 95.27909774
  1.25026534 10.46370424 74.34591751 79.79654223]


dtype('float64')

In [25]:
# Create an array of numbers from 0 to 75 in increments of 5.
print (np.arange(0,80,5))

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75]
